%% Purpose: Display a salsa bottle for openning message 
function disp_salsa_bottle()
    disp("-------------------------------------------------------")
    disp("Welcome to:")
    disp("Shabbir Antoine Louis Sepehr Algorithm (SALSA) Package")
    disp("                 __________   ")
    disp("                [__________]  ")
    disp("               // ******** \\ ")
    disp("              || ********** ||")
    disp("              || ********** ||")
    disp("              || ********** ||")
    disp("              ||============||")
    disp("              ||    SALSA   ||")
    disp("              ||============||")
    disp("              || ********** ||")
    disp("               \\__________//")
    disp("                \__________/ ") 
    disp("-------------------------------------------------------")   
end