%% Purpose: Unique Salsa Recipe
% Prints a unique salsa recipe generated by ChatGPT
% Randomly chooses a recipe based on dice roll
% Recipes included in ./+recipes
function spill_the_beans()
    recipe_number = randi([1 6]);
    div = "---------";
    fprintf("%sSpilling the beans on recipe #%d%s\n", div, recipe_number, div);
    file_path = "./+salsa/+spicy/+recipes/recipe_" + num2str(recipe_number) + ".txt";
    disp(fileread(file_path))
end