function [kernel, b, J] = test_blur_and_noise(file_path, blur_type, noise_type, pad_type)
    arguments
        file_path char {mustBeFile(file_path)}
        blur_type string {mustBeMember(blur_type, ...
                                        {'average',  ...
                                         'disk',     ...
                                         'gaussian'  ...
                                         'log'       ...
                                         'laplacian' ...
                                         'motion'})}
        noise_type string {mustBeMember(noise_type, ...
                                        {'gaussian',     ...
                                         'poisson',      ...
                                         'salt & pepper' ...
                                         'speckle'})}
        pad_type string {mustBeMember(pad_type, ...
                                        {'symmetric', ...
                                         'replicate', ...
                                         'circular'})} = img.defaults.get_filter_def()
    end

    % Load Image
    show_raw = true;
    I = img.load(file_path, show_raw);
    
    % Apply Preprocessing
    to_grayscale = true; 
    resize       = true;
    show_preproc = true;
    I = img.pre_process(I, to_grayscale, resize, show_preproc);

    % Blur Image
    [kernel, b] = img.add_blur(I, blur_type, pad_type);

    % Add Noise
    J = img.add_noise(b, noise_type);
end

